package:
    name: sls_detector
    version: developer

build:
  number: 0

source:
    path: ..

requirements:
    build:
        - python
        - cmake
        - gcc
        - libstdcxx-ng
        - libgcc-ng
        - libpng >=1.6.32,<1.6.35
        - setuptools
        - sls_detector_lib developer
        - pyzmq
        - pybind11

    run:
        - python
        - numpy
        - sls_detector_lib developer
        - pyzmq
        - libstdcxx-ng
        - libgcc-ng


test:
      imports:
        - sls_detector



about:
    summary: "Interacting with detectors"
